package miun.dt170g.application_restaurant.entities;

public class MenuItemOrders {
    private int menuItemId;
    /* order id is not needed, as it is
    generated by the server when the order
    is created */
    private int quantity;

    // Constructors
    public MenuItemOrders(int menuItemId, int quantity) {
        this.menuItemId = menuItemId;
        this.quantity = quantity;
    }

    // Getters and setters
    public int getMenuItemId() {
        return menuItemId;
    }

    public void setMenuItemId(int menuItemId) {
        this.menuItemId = menuItemId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // toString, equals, and hashCode methods can be overridden as needed
}
