package miun.dt170g.application_restaurant;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import miun.dt170g.application_restaurant.entities.AlacarteMenuItem;
import miun.dt170g.application_restaurant.entities.Employee;
import miun.dt170g.application_restaurant.entities.MenuItemOrders;
import miun.dt170g.application_restaurant.entities.Order;
import miun.dt170g.application_restaurant.entities.Table;
import miun.dt170g.application_restaurant.retrofit.RetrofitClient;
import miun.dt170g.application_restaurant.retrofit.RetrofitInterface;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        RetrofitInterface apiData = RetrofitClient.create();

        Order newOrder = new Order();
        /* order id does not need to be set here;
        * it's generated by the server
        * */
        newOrder.setTableNum(10);

        // Example menu items - this part is pseudo-code and will depend on your actual MenuItemOrder class

        MenuItemOrders item1 = new MenuItemOrders(1, 3); // MenuItem ID 1, Quantity 3
        MenuItemOrders item2 = new MenuItemOrders(2, 2); // MenuItem ID 2, Quantity 2

        newOrder.addMenuItemOrder(item1);
        newOrder.addMenuItemOrder(item2);

        Call<Void> orderCall = apiData.sendOrder(newOrder);
        orderCall.enqueue(new Callback<Void>() {
            @Override
            public void onResponse(Call<Void> call, Response<Void> response) {
                if (response.isSuccessful()) {
                    // Handle successful response
                    Log.e("Success", "order sent successfully");
                } else {
                    // Handle unsuccessful response
                    Log.e("API Error", "Error code: " + response.code());
                }
            }
            @Override
            public void onFailure(Call<Void> call, Throwable t) {
                // Handle failure
                Log.e("API Error", "Failed to send order " + t.getMessage(), t);
            }
        });
    }
}